name: Build Swatches

on:
  workflow_dispatch:
  push:
    paths:
      - 'assets/brochure.pdf'
      - 'populate_swatches.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run extractor
        run: python populate_swatches.py

      - name: Commit swatches
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add swatches swatches_raw || true
          git commit -m "Build swatches from brochure.pdf" || echo "No changes to commit"
          git push

